export const AppReference = {
    Application:
    {
        Shell: "App_Shell",
    },
    Navigation: {
        AreaButton: "Nav_AreaButton",
        AreaMenu: "Nav_AreaMenu",
        AreaMoreMenu: "Nav_AreaMoreMenu",
        SubAreaContainer: "Nav_SubAreaContainer",
        WebAppMenuButton: "Nav_WebAppMenuButton",
        UCIAppMenuButton: "Nav_UCIAppMenuButton",
        SiteMapLauncherButton: "Nav_SiteMapLauncherButton",
        SiteMapLauncherCloseButton: "Nav_SiteMapLauncherCloseButton",
        SiteMapAreaMoreButton: "Nav_SiteMapAreaMoreButton",
        SiteMapSingleArea: "Nav_SiteMapSingleArea",
        AppMenuContainer: "Nav_AppMenuContainer",
        SettingsLauncherBar: "Nav_SettingsLauncherBar",
        SettingsLauncher: "Nav_SettingsLauncher",
        GuidedHelp: "Nav_GuidedHelp",
        AdminPortal: "Nav_AdminPortal",
        AdminPortalButton: "Nav_AdminPortalButton",
        SearchButton: "Nav_SearchButton",
        Search: "Nav_Search",
        QuickLaunchMenu: "Nav_QuickLaunchMenu",
        QuickLaunchButton: "Nav_QuickLaunchButton",
        QuickCreateButton: "Nav_QuickCreateButton",
        QuickCreateMenuList: "Nav_QuickCreateMenuList",
        QuickCreateMenuItems: "Nav_QuickCreateMenuItems",
        PinnedSitemapEntity: "Nav_PinnedSitemapEntity",
        SitemapMenuGroup: "Nav_SitemapMenuGroup",
        SitemapMenuItems: "Nav_SitemapMenuItems",
        SitemapSwitcherButton: "Nav_SitemapSwitcherButton",
        SitemapSwitcherFlyout: "Nav_SitemapSwitcherFlyout",
        UCIAppContainer: "Nav_UCIAppContainer",
        UCIAppTile: "Nav_UCIAppTile",
    },
    Grid: {
        Container: "Grid_Container",
        QuickFind: "Grid_QuickFind",
        FirstPage: "Grid_FirstPage",
        NextPage: "Grid_NextPage",
        PreviousPage: "Grid_PreviousPage",
        SelectAll: "Grid_SelectAll",
        ShowChart: "Grid_ShowChart",
        HideChart: "Grid_HideChart",
        JumpBar: "Grid_JumpBar",
        FilterByAll: "Grid_FilterByAll",
        RowsContainer: "Grid_RowsContainer",
        Rows: "Grid_Rows",
        ChartSelector: "Grid_ChartSelector",
        ChartViewList: "Grid_ChartViewList",
        GridSortColumn: "Grid_SortColumn",
        CellContainer: "Grid_CellContainer",
        ViewSelector: "Grid_ViewSelector",
        ViewContainer: "Grid_ViewContainer",
        SubArea: "Grid_SubArea",
    },
    Entity: {
        FormContext: "Entity_FormContainer",
        FormSelector: "Entity_FormSelector",
        HeaderTitle: "Entity_HeaderTitle",
        HeaderContext: "Entity_HeaderContext",
        Save: "Entity_Save",
        TextFieldContainer: "Entity_TextFieldContainer",
        TextFieldLabel: "Entity_TextFieldLabel",
        TextFieldValue: "Entity_TextFieldValue",
        TextFieldLookup: "Entity_TextFieldLookup",
        TextFieldLookupSearchButton: "Entity_TextFieldLookupSearchButton",
        TextFieldLookupMenu: "Entity_TextFieldLookupMenu",
        LookupFieldExistingValue: "Entity_LookupFieldExistingValue",
        LookupFieldDeleteExistingValue: "Entity_LookupFieldDeleteExistingValue",
        LookupFieldExpandCollapseButton: "Entity_LookupFieldExpandCollapseButton",
        LookupFieldNoRecordsText: "Entity_LookupFieldNoRecordsText",
        LookupFieldResultList: "Entity_LookupFieldResultList",
        LookupFieldResultListItem: "Entity_LookupFieldResultListItem",
        LookupFieldHoverExistingValue: "Entity_LookupFieldHoverExistingValue",
        LookupResultsDropdown: "Entity_LookupResultsDropdown",
        OptionSetFieldContainer: "Entity_OptionSetFieldContainer",
        TextFieldLookupFieldContainer: "Entity_TextFieldLookupFieldContainer",
        RecordSetNavigator: "Entity_RecordSetNavigator",
        RecordSetNavigatorOpen: "Entity_RecordSetNavigatorOpen",
        RecordSetNavList: "Entity_RecordSetNavList",
        RecordSetNavCollapseIcon: "Entity_RecordSetNavCollapseIcon",
        RecordSetNavCollapseIconParent: "Entity_RecordSetNavCollapseIconParent",
        FieldControlDateTimeContainer: "Entity_FieldControlDateTimeContainer",
        FieldControlDateTimeInputUCI: "Entity_FieldControlDateTimeInputUCI",
        FieldControlDateTimeTimeInputUCI: "Entity_FieldControlDateTimeTimeInputUCI",
        Delete: "Entity_Delete",
        Assign: "Entity_Assign",
        SwitchProcess: "Entity_SwitchProcess",
        CloseOpportunityWin: "Entity_CloseOpportunityWin",
        CloseOpportunityLoss: "Entity_CloseOpportunityLoss",
        ProcessButton: "Entity_Process",
        SwitchProcessDialog: "Entity_SwitchProcessDialog",
        TabList: "Entity_TabList",
        Tab: "Entity_Tab",
        MoreTabs: "Entity_MoreTabs",
        MoreTabsMenu: "Entity_MoreTabsMenu",
        SubTab: "Entity_SubTab",
        EntityFooter: "Entity_Footer",
        SubGridTitle: "Entity_SubGridTitle",
        SubGridContents: "Entity_SubGridContents",
        SubGridList: "Entity_SubGridList",
        SubGridViewPickerButton: "Entity_SubGridViewPickerButton",
        SubGridViewPickerFlyout: "Entity_SubGridViewPickerFlyout",
        SubGridCommandBar: "Entity_SubGridCommandBar",
        SubGridOverflowContainer: "Entity_SubGridOverflowContainer",
        SubGridOverflowButton: "Entity_SubGridOverflowButton",
        SubGridHighDensityList: "Entity_SubGridHighDensityList",
        EditableSubGridList: "Entity_EditableSubGridList",
        EditableSubGridListCells: "Entity_EditableSubGridListCells",
        EditableSubGridListCellRows: "Entity_EditableSubGridListCellRows",
        SubGridCells: "Entity_SubGridCells",
        SubGridRows: "Entity_SubGridRows",
        SubGridRowsHighDensity: "Entity_SubGridRowsHighDensity",
        SubGridDataRowsEditable: "Entity_SubGridDataRowsEditable",
        SubGridHeaders: "Entity_SubGridHeaders",
        SubGridHeadersHighDensity: "Entity_SubGridHeadersHighDensity",
        SubGridHeadersEditable: "Entity_SubGridHeadersEditable",
        SubGridRecordCheckbox: "Entity_SubGridRecordCheckbox",
        SubGridSearchBox: "Entity_SubGridSearchBox",
        SubGridAddButton: "Entity_SubGridAddButton",
        FieldLookupButton: "Entity_FieldLookupButton",
        SearchButtonIcon: "Entity_SearchButtonIcon",
        DuplicateDetectionWindowMarker: "Entity_DuplicateDetectionWindowMarker",
        DuplicateDetectionGridRows: "Entity_DuplicateDetectionGridRows",
        DuplicateDetectionIgnoreAndSaveButton: "Entity_DuplicateDetectionIgnoreAndSaveButton",
        FooterStatusValue: "Entity_FooterStatusField",
        FooterMessageValue: "Entity_FooterMessage",
        EntityBooleanFieldRadioContainer: "Entity_BooleanFieldRadioContainer",
        EntityBooleanFieldRadioTrue: "Entity_BooleanFieldRadioTrue",
        EntityBooleanFieldRadioFalse: "Entity_BooleanFieldRadioFalse",
        EntityBooleanFieldButtonContainer: "Entity_BooleanFieldButton",
        EntityBooleanFieldButtonTrue: "Entity_BooleanFieldButtonTrue",
        EntityBooleanFieldButtonFalse: "Entity_BooleanFieldButtonFalse",
        EntityBooleanFieldCheckboxContainer: "Entity_BooleanFieldCheckboxContainer",
        EntityBooleanFieldCheckbox: "Entity_BooleanFieldCheckbox",
        EntityBooleanFieldList: "Entity_BooleanFieldList",
        EntityBooleanFieldFlipSwitchLink: "Entity_BooleanFieldFlipSwitchLink",
        EntityBooleanFieldFlipSwitchContainer: "Entity_BooleanFieldFlipSwitchContainer",
        EntityBooleanFieldToggle: "Entity_BooleanFieldToggle",
        EntityOptionsetStatusCombo: "Entity_OptionsetStatusCombo",
        EntityOptionsetStatusComboButton: "Entity_OptionsetStatusComboButton",
        EntityOptionsetStatusComboList: "Entity_OptionsetStatusComboList",
        EntityOptionsetStatusTextValue: "Entity_OptionsetStatusTextValue",
        FormMessageBar: "Entity_FormMessageBar",
        FormMessageBarTypeIcon: "Entity_FormMessageBarTypeIcon",
        FormNotifcationBar: "Entity_FormNotifcationBar",
        FormNotifcationExpandButton: "Entity_FormNotifcationExpandButton",
        FormNotifcationFlyoutRoot: "Entity_FormNotifcationFlyoutRoot",
        FormNotifcationList: "Entity_FormNotifcationList",
        FormNotifcationTypeIcon: "Entity_FormNotifcationTypeIcon",
    },
    Header: {
        Container: "Entity_Header",
        Flyout: "Entity_Header_Flyout",
        FlyoutButton: "Entity_Header_FlyoutButton",
        LookupFieldContainer: "Entity_Header_LookupFieldContainer",
        TextFieldContainer: "Entity_Header_TextFieldContainer",
        OptionSetFieldContainer: "Entity_Header_OptionSetFieldContainer",
        DateTimeFieldContainer: "Entity_Header_DateTimeFieldContainer",
    },
    CommandBar: {
        Container: "Cmd_Container",
        ContainerGrid: "Cmd_ContainerGrid",
        MoreCommandsMenu: "Cmd_MoreCommandsMenu",
        Button: "Cmd_Button",
    },
    Timeline: {
        SaveAndClose: "Timeline_SaveAndClose",
    },
    Dashboard: {
        DashboardSelector: "Dashboard_Selector",
        DashboardItem: "Dashboard_Item",
        DashboardItemUCI: "Dashboard_Item_UCI",
    },
    MultiSelect: {
        DivContainer: "MultiSelect_DivContainer",
        InputSearch: "MultiSelect_InputSearch",
        SelectedRecord: "MultiSelect_SelectedRecord",
        SelectedRecordButton: "MultiSelect_SelectedRecord_Button",
        SelectedRecordLabel: "MultiSelect_SelectedRecord_Label",
        Flyout: "MultiSelect_Flyout",
        FlyoutList: "MultiSelect_FlyoutList",
        ExpandCollapseButton: "MultiSelect_ExpandCollapseButton",
    },
    GlobalSearch: {
        CategorizedSearchButton: "Search_CategorizedSearchButton",
        RelevanceSearchButton: "Search_RelevanceSearchButton",
        Text: "Search_Text",
        Filter: "Search_Filter",
        Results: "Search_Result",
        Container: "Search_Container",
        EntityContainer: "Search_EntityContainer",
        Records: "Search_Records",
        Type: "Search_Type",
        GroupContainer: "Search_GroupContainer",
        FilterValue: "Search_FilterValue",
        RelevanceResultsContainer: "Search_RelevanceResultsContainer",
        RelevanceResults: "Search_RelevanceResults",
    },
    BusinessProcessFlow: {
        NextStage_UCI: "BPF_NextStage_UCI",
        Flyout_UCI: "BPF_Flyout_UCI",
        NextStageButton: "BPF_NextStageButton_UCI",
        SetActiveButton: "BPF_SetActiveButton",
        BusinessProcessFlowFieldName: "BPF_FieldName_UCI",
        BusinessProcessFlowFormContext: "BPF_FormContext",
        TextFieldContainer: "BPF_TextFieldContainer",
        FieldSectionItemContainer: "BPF_FieldSectionItemContainer",
        TextFieldLabel: "BPF_TextFieldLabel",
        BooleanFieldContainer: "BPF_BooleanFieldContainer",
        DateTimeFieldContainer: "BPF_DateTimeFieldContainer",
        FieldControlDateTimeInputUCI: "BPF_FieldControlDateTimeInputUCI",
        PinStageButton: "BPF_PinStageButton",
        CloseStageButton: "BPF_CloseStageButton",
    },
    Dialogs: {
        CloseOpportunity:
        {
            Ok: "CloseOpportunityDialog_OKButton",
            Cancel: "CloseOpportunityDialog_CancelButton",
            ActualRevenueId: "Dialog_ActualRevenue",
            CloseDateId: "Dialog_CloseDate",
            DescriptionId: "Dialog_Description",
        },
        CloseActivity: {
            Close: "CloseActivityDialog_CloseButton",
            Cancel: "CloseActivityDialog_CancelButton",
        },
        AssignDialogUserTeamLookupResults: "AssignDialog_UserTeamLookupResults",
        AssignDialogOKButton: "AssignDialog_OKButton",
        AssignDialogToggle: "AssignDialog_ToggleField",
        ConfirmButton: "Dialog_ConfirmButton",
        CancelButton: "Dialog_CancelButton",
        DuplicateDetectionIgnoreSaveButton: "DuplicateDetectionDialog_IgnoreAndSaveButton",
        DuplicateDetectionCancelButton: "DuplicateDetectionDialog_CancelButton",
        PublishConfirmButton: "Dialog_PublishConfirmButton",
        PublishCancelButton: "Dialog_PublishCancelButton",
        SetStateDialog: "Dialog_SetStateDialog",
        SetStateActionButton: "Dialog_SetStateActionButton",
        SetStateCancelButton: "Dialog_SetStateCancelButton",
        SwitchProcessDialog: "Entity_SwitchProcessDialog",
        SwitchProcessDialogOK: "Entity_SwitchProcessDialogOK",
        ActiveProcessGridControlContainer: "Entity_ActiveProcessGridControlContainer",
        DialogContext: "Dialog_DialogContext",
        SwitchProcessContainer: "Dialog_SwitchProcessContainer",
    }
    ,
    QuickCreate: {
        QuickCreateFormContext: "QuickCreate_FormContext",
        SaveButton: "QuickCreate_SaveButton",
        SaveAndCloseButton: "QuickCreate_SaveAndCloseButton",
        CancelButton: "QuickCreate_CancelButton",
    }
    ,
    Lookup: {
        RelatedEntityLabel: "Lookup_RelatedEntityLabel",
        ChangeViewButton: "Lookup_ChangeViewButton",
        ViewRows: "Lookup_ViewRows",
        LookupResultRows: "Lookup_ResultRows",
        NewButton: "Lookup_NewButton",
        RecordList: "Lookup_RecordList",
    }
    ,
    Related: {
        CommandBarButton: "Related_CommandBarButton",
        CommandBarSubButton: "Related_CommandBarSubButton",
        CommandBarOverflowContainer: "Related_CommandBarOverflowContainer",
        CommandBarOverflowButton: "Related_CommandBarOverflowButton",
        CommandBarButtonList: "Related_CommandBarButtonList",
    }
    ,
    Field: {
        ReadOnly: "Field_ReadOnly",
        Required: "Field_Required",
        RequiredIcon: "Field_RequiredIcon",
    },
    PerformanceWidget: {
        Container: "Performance_Widget",
        Page: "Performance_WidgetPage",
    }
}

export const AppElements: { Xpath: Record<string, string> } = {
    Xpath: {
        //Application 
        "App_Shell": "//*[@id=\"ApplicationShell\"]",

        //Navigation
        "Nav_AreaButton": "//button[@id='areaSwitcherId']",
        "Nav_AreaMenu": "//*[@data-lp-id='sitemap-area-switcher-flyout']",
        "Nav_AreaMoreMenu": "//ul[@role=\"menubar\"]",
        "Nav_SubAreaContainer": "//*[@data-id=\"navbar-container\"]/div/ul",
        "Nav_WebAppMenuButton": "//*[@id=\"TabArrowDivider\"]/a",
        "Nav_UCIAppMenuButton": "//button[@data-id=\"navbar-switch-app\"]",
        "Nav_SiteMapLauncherButton": "//button[@data-lp-id=\"sitemap-launcher\"]",
        "Nav_SiteMapLauncherCloseButton": "//button[@data-id='navbutton']",
        "Nav_SiteMapAreaMoreButton": "//button[@data-lp-id=\"sitemap-areaBar-more-btn\"]",
        "Nav_SiteMapSingleArea": "//li[translate(@data-text,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz') = '[NAME]']",
        "Nav_AppMenuContainer": "//*[@id=\"taskpane-scroll-container\"]",
        "Nav_SettingsLauncherBar": "//button[@data-id='[NAME]Launcher']",
        "Nav_SettingsLauncher": "//div[@id='[NAME]Launcher']",
        "Nav_GuidedHelp": "//*[@id=\"helpLauncher\"]/button",
        //{ "Nav_AdminPortal"       , "//*[@id=(\"id-5\")]"},
        "Nav_AdminPortal": "//*[contains(@data-id,'officewaffle')]",
        "Nav_AdminPortalButton": "//*[@id=(\"O365_AppTile_Admin\")]",
        "Nav_SearchButton": "//*[@id=\"searchLauncher\"]/button",
        "Nav_Search": "//*[@id=\"categorizedSearchInputAndButton\"]",
        "Nav_QuickLaunchMenu": "//div[contains(@data-id,'quick-launch-bar')]",
        "Nav_QuickLaunchButton": "//li[contains(@title, '[NAME]')]",
        "Nav_QuickCreateButton": "//button[contains(@data-id,'quickCreateLauncher')]",
        "Nav_QuickCreateMenuList": "//ul[contains(@id,'MenuSectionItemsquickCreate')]",
        "Nav_QuickCreateMenuItems": "//li[@role='menuitem']",
        "Nav_PinnedSitemapEntity": "//li[contains(@data-id,'sitemap-entity-Pinned') and contains(@role,'treeitem')]",
        "Nav_SitemapMenuGroup": "//ul[@role=\"group\"]",
        "Nav_SitemapMenuItems": "//li[contains(@data-id,'sitemap-entity')]",
        "Nav_SitemapSwitcherButton": "//button[contains(@data-id,'sitemap-areaSwitcher-expand-btn')]",
        "Nav_SitemapSwitcherFlyout": "//div[contains(@data-lp-id,'sitemap-area-switcher-flyout')]",
        "Nav_UCIAppContainer": "//div[@id='AppLandingPageContentContainer']",
        "Nav_UCIAppTile": "//div[@data-type='app-title' and @title='[NAME]']",


        //Grid
        "Grid_Container": "//div[@data-type=\"Grid\"]",
        "Grid_QuickFind": "//*[contains(@id, \'quickFind_text\')]",
        "Grid_NextPage": "//button[contains(@data-id,'moveToNextPage')]",
        "Grid_PreviousPage": "//button[contains(@data-id,'moveToPreviousPage')]",
        "Grid_FirstPage": "//button[contains(@data-id,'loadFirstPage')]",
        "Grid_SelectAll": "//button[contains(@title,'Select All')]",
        "Grid_ShowChart": "//button[contains(@aria-label,'Show Chart')]",
        "Grid_JumpBar": "//*[@id=\"JumpBarItemsList\"]",
        "Grid_FilterByAll": "//*[@id=\"All_link\"]",
        "Grid_RowsContainer": "//div[contains(@role,'grid')]",
        "Grid_Rows": "//div[contains(@role,'row')]",
        "Grid_ChartSelector": "//span[contains(@id,'ChartSelector')]",
        "Grid_ChartViewList": "//ul[contains(@role,'listbox')]",
        "Grid_SortColumn": "//div[@data-type='Grid']//div[@title='[COLNAME]']//div[contains(@class,'header')]",
        "Grid_CellContainer": "//div[@role='grid'][@data-id='grid-cell-container']",
        "Grid_ViewSelector": "//span[contains(@id,'ViewSelector')]",
        "Grid_ViewContainer": "//ul[contains(@id,'ViewSelector')]",
        "Grid_SubArea": "//*[contains(@data-id,'[NAME]')]",


        //Entity
        "Entity_Assign": "//button[contains(@data-id,'Assign')]",
        "Entity_CloseOpportunityWin": "//button[contains(@data-id,'MarkAsWon')]",
        "Entity_CloseOpportunityLoss": "//button[contains(@data-id,'MarkAsLost')]",
        "Entity_Delete": "//button[contains(@data-id,'Delete')]",
        "Entity_FormContainer": "//*[@data-id='editFormRoot']",
        "Entity_FormSelector": "//*[@data-id='form-selector']",
        "Entity_HeaderTitle": "//*[@data-id='header_title']",
        "Entity_HeaderContext": ".//div[@data-id='headerFieldsFlyout']",
        "Entity_Process": "//button[contains(@data-id,'MBPF.ConvertTo')]",
        "Entity_Save": "//button[contains(@data-id, 'form-save-btn')]",
        "Entity_SwitchProcess": "//button[contains(@data-id,'SwitchProcess')]",
        "Entity_TextFieldContainer": ".//*[contains(@id, \'[NAME]-FieldSectionItemContainer\')]",
        "Entity_TextFieldLabel": ".//label[contains(@id, \'[NAME]-field-label\')]",
        "Entity_TextFieldValue": ".//input[contains(@data-id, \'[NAME].fieldControl\')]",
        "Entity_TextFieldLookup": ".//*[contains(@id, \'systemuserview_id.fieldControl-LookupResultsDropdown')]",
        "Entity_TextFieldLookupSearchButton": ".//button[contains(@data-id, '[NAME].fieldControl-LookupResultsDropdown_[NAME]_search')]",
        "Entity_TextFieldLookupMenu": "//div[contains(@data-id, '[NAME].fieldControl-LookupResultsDropdown_[NAME]') and contains(@data-id,'tabContainer')]",
        "Entity_LookupFieldExistingValue": ".//*[contains(@data-id, '[NAME].fieldControl-LookupResultsDropdown_[NAME]_selected_tag')]",
        "Entity_LookupFieldDeleteExistingValue": ".//*[contains(@data-id, '[NAME].fieldControl-LookupResultsDropdown_[NAME]_selected_tag_delete')]",
        "Entity_LookupFieldExpandCollapseButton": ".//button[contains(@data-id,'[NAME].fieldControl-LookupResultsDropdown_[NAME]_expandCollapse')]/descendant::label[not(text()='+0')]",
        "Entity_LookupFieldNoRecordsText": ".//*[@data-id=\'[NAME].fieldControl-LookupResultsDropdown_[NAME]_No_Records_Text']",
        "Entity_LookupFieldResultList": ".//*[contains(@data-id, '[NAME].fieldControl-LookupResultsDropdown_[NAME]_tab')]",
        "Entity_LookupFieldResultListItem": ".//*[contains(@data-id, '[NAME].fieldControl-LookupResultsDropdown_[NAME]_resultsContainer')]",
        "Entity_LookupFieldHoverExistingValue": ".//*[contains(@data-id, '[NAME].fieldControl-LookupResultsDropdown_[NAME]_SelectedRecordList')]",
        "Entity_TextFieldLookupFieldContainer": ".//div[@data-id='[NAME].fieldControl-Lookup_[NAME]']",
        "Entity_RecordSetNavigatorOpen": "//button[contains(@data-lp-id, 'recordset-navigator')]",
        "Entity_RecordSetNavigator": "//button[contains(@data-lp-id, 'recordset-navigator')]",
        "Entity_RecordSetNavList": "//ul[contains(@data-id, 'recordSetNavList')]",
        "Entity_RecordSetNavCollapseIcon": "//*[contains(@data-id, 'recordSetNavCollapseIcon')]",
        "Entity_RecordSetNavCollapseIconParent": "//*[contains(@data-id, 'recordSetNavCollapseIcon')]",
        "Entity_TabList": "//ul[contains(@id, \"tablist\")]",
        "Entity_Tab": ".//li[@title='{0}']",
        "Entity_MoreTabs": ".//button[@data-id='more_button']",
        "Entity_MoreTabsMenu": "//div[@id='__flyoutRootNode']",
        "Entity_SubTab": "//div[@id=\"__flyoutRootNode\"]//span[text()=\"{0}\"]",
        "Entity_FieldControlDateTimeContainer": "//div[@data-id='[NAME]-FieldSectionItemContainer']",
        "Entity_FieldControlDateTimeInputUCI": ".//*[contains(@data-id, '[FIELD].fieldControl-date-time-input')]",
        "Entity_FieldControlDateTimeTimeInputUCI": ".//div[contains(@data-id,'[FIELD].fieldControl._timecontrol-datetime-container')]/div/div/input",
        "Entity_LookupResultsDropdown": "//*[contains(@data-id, '[NAME].fieldControl-LookupResultsDropdown_[NAME]_tab')]",
        "Entity_Footer": "//div[contains(@id,'footerWrapper')]",
        "Entity_SubGridTitle": "//div[contains(text(), '[NAME]')]",
        "Entity_SubGridContents": "//div[@id=\"dataSetRoot_[NAME]\"]",
        "Entity_SubGridList": ".//ul[contains(@id, \"[NAME]-GridList\")]",
        "Entity_SubGridViewPickerButton": ".//span[contains(@id, 'ViewSelector') and contains(@role, 'button')]",
        "Entity_SubGridViewPickerFlyout": "//div[contains(@id, 'ViewSelector') and contains(@flyoutroot, 'flyoutRootNode')]",
        "Entity_SubGridCommandBar": ".//ul[contains(@data-id, 'CommandBar')]",
        "Entity_SubGridOverflowContainer": ".//div[contains(@data-id, 'flyoutRootNode')]",
        "Entity_SubGridOverflowButton": ".//li[contains(@aria-label, '[NAME]')]",
        "Entity_SubGridHighDensityList": ".//div[contains(@data-lp-id, \"ReadOnlyGrid|[NAME]\") and contains(@class, 'editableGrid')]",
        "Entity_EditableSubGridList": ".//div[contains(@data-lp-id, \"[NAME]\") and contains(@class, 'editableGrid') and not(contains(@class, 'readonly'))]",
        "Entity_EditableSubGridListCells": ".//div[contains(@wj-part, 'cells') and contains(@class, 'wj-cells') and contains(@role, 'grid')]",
        "Entity_EditableSubGridListCellRows": ".//div[contains(@class, 'wj-row') and contains(@role, 'row')]",
        "Entity_SubGridCells": ".//div[contains(@role,'gridcell')]",
        "Entity_SubGridRows": ".//div[contains(@class,'wj-row')]",
        "Entity_SubGridRowsHighDensity": ".//div[contains(@class,'wj-row') and contains(@role, 'row') and contains(@aria-label, 'Data')]",
        "Entity_SubGridDataRowsEditable": ".//div[contains(@class,'wj-row') and contains(@role, 'row') and contains(@aria-label, 'Data')]",
        "Entity_SubGridHeaders": ".//div[contains(@class,'grid-header-text')]",
        "Entity_SubGridHeadersHighDensity": ".//div[contains(@class, 'wj-colheaders') and contains(@wj-part, 'chcells')]/div/div",
        "Entity_SubGridHeadersEditable": ".//div[contains(@class,'wj-row') and contains(@role, 'row') and contains(@aria-label, 'Header')]/div",
        "Entity_SubGridRecordCheckbox": "//div[contains(@data-id,'cell-[INDEX]-1') and contains(@data-lp-id,'[NAME]')]",
        "Entity_SubGridSearchBox": ".//div[contains(@data-id, 'data-set-quickFind-container')]",
        "Entity_SubGridAddButton": "//button[contains(@data-id,'[NAME].AddNewStandard')]/parent::li/parent::ul[contains(@data-lp-id, 'commandbar-SubGridStandard:[NAME]')]",
        "Entity_FieldLookupButton": "//button[contains(@data-id,'[NAME]_search')]",
        "Entity_SearchButtonIcon": "//span[contains(@data-id,'microsoftIcon_searchButton')]",
        "Entity_DuplicateDetectionWindowMarker": "//div[contains(@data-id,'ManageDuplicates')]",
        "Entity_DuplicateDetectionGridRows": "//div[contains(@class,'data-selectable')]",
        "Entity_DuplicateDetectionIgnoreAndSaveButton": "//button[contains(@data-id,'ignore_save')]",
        "Entity_FooterStatusField": ".//span[contains(@role,'status')]",
        "Entity_FooterMessage": ".//span[contains(@data-id,'footer-message')]",
        "Entity_BooleanFieldRadioContainer": "//div[contains(@data-id, '[NAME].fieldControl-checkbox-container') and contains(@role,'radiogroup')]",
        "Entity_BooleanFieldRadioTrue": "//div[contains(@data-id, '[NAME].fieldControl-checkbox-containercheckbox-inner-second')]",
        "Entity_BooleanFieldRadioFalse": "//div[contains(@data-id, '[NAME].fieldControl-checkbox-containercheckbox-inner-first')]",
        "Entity_BooleanFieldCheckboxContainer": "//div[contains(@data-id, '[NAME].fieldControl-checkbox-container')]",
        "Entity_BooleanFieldCheckbox": "//input[contains(@data-id, '[NAME].fieldControl-checkbox-toggle')]",
        "Entity_BooleanFieldList": "//select[contains(@data-id, '[NAME].fieldControl-checkbox-select')]",
        "Entity_BooleanFieldFlipSwitchLink": "//div[contains(@data-id, '[NAME]-FieldSectionItemContainer')]",
        "Entity_BooleanFieldFlipSwitchContainer": "//div[@data-id= '[NAME].fieldControl_container']",
        "Entity_BooleanFieldButton": "//div[contains(@data-id, '[NAME].fieldControl_container')]",
        "Entity_BooleanFieldButtonTrue": ".//label[contains(@class, 'first-child')]",
        "Entity_BooleanFieldButtonFalse": ".//label[contains(@class, 'last-child')]",
        "Entity_BooleanFieldToggle": "//div[contains(@data-id, '[NAME].fieldControl-toggle-container')]",
        "Entity_OptionSetFieldContainer": ".//div[@data-id='[NAME].fieldControl-option-set-container']",
        "Entity_OptionsetStatusCombo": "//div[contains(@data-id, '[NAME].fieldControl-pickliststatus-comboBox')]",
        "Entity_OptionsetStatusComboButton": "//div[contains(@id, '[NAME].fieldControl-pickliststatus-comboBox_button')]",
        "Entity_OptionsetStatusComboList": "//ul[contains(@id, '[NAME].fieldControl-pickliststatus-comboBox_list')]",
        "Entity_OptionsetStatusTextValue": "//span[contains(@id, '[NAME].fieldControl-pickliststatus-comboBox_text-value')]",
        "Entity_FormMessageBar": "//*[@id=\"notificationMessageAndButtons\"]/div/div/span",
        "Entity_FormMessageBarTypeIcon": ".//span[contains(@data-id,'formReadOnlyIcon')]",
        "Entity_FormNotifcationBar": "//div[contains(@data-id, 'notificationWrapper')]",
        "Entity_FormNotifcationTypeIcon": ".//span[contains(@id,'notification_icon_')]",
        "Entity_FormNotifcationExpandButton": ".//span[@id='notificationExpandIcon']",
        "Entity_FormNotifcationFlyoutRoot": "//div[@id='__flyoutRootNode']",
        "Entity_FormNotifcationList": ".//ul[@data-id='notificationList']",

        //Entity Header
        "Entity_Header": "//div[contains(@data-id,'form-header')]",
        "Entity_Header_Flyout": "//div[@data-id='headerFieldsFlyout']",
        "Entity_Header_FlyoutButton": "//button[contains(@id,'headerFieldsExpandButton')]",
        "Entity_Header_LookupFieldContainer": "//div[@data-id='header_[NAME].fieldControl-Lookup_[NAME]']",
        "Entity_Header_TextFieldContainer": "//div[@data-id='header_[NAME].fieldControl-text-box-container']",
        "Entity_Header_OptionSetFieldContainer": "//div[@data-id='header_[NAME]']",
        "Entity_Header_DateTimeFieldContainer": "//div[@data-id='header_[NAME]-FieldSectionItemContainer']",

        //CommandBar
        "Cmd_Container": "//ul[contains(@data-lp-id,\"commandbar-Form\")]",
        "Cmd_ContainerGrid": "//ul[contains(@data-lp-id,\"commandbar-HomePageGrid\")]",
        "Cmd_MoreCommandsMenu": "//*[@id=\"__flyoutRootNode\"]",
        "Cmd_Button": "//*[contains(text(),'[NAME]')]",

        //GlobalSearch
        "Search_RelevanceSearchButton": "//div[@aria-label=\"Search box\"]//button",
        "Search_CategorizedSearchButton": "//button[contains(@data-id,'search-submit-button')]",
        "Search_Text": "//input[@aria-label=\"Search box\"]",
        "Search_Filter": "//select[@aria-label=\"Filter with\"]",
        "Search_Container": "//div[@id=\"searchResultList\"]",
        "Search_EntityContainer": "//div[@id=\"View[NAME]\"]",
        "Search_Records": "//li[@role=\"row\"]",
        "Search_Type": "//select[contains(@data-id,\"search-root-selector\")]",
        "Search_GroupContainer": "//label[contains(text(), '[NAME]')]/parent::div",
        "Search_FilterValue": "//label[contains(text(), '[NAME]')]",
        "Search_RelevanceResultsContainer": "//div[@aria-label=\"Search Results\"]",
        "Search_RelevanceResults": "//li//label[contains(text(), '[ENTITY]')]",

        //Timeline
        "Timeline_SaveAndClose": "//button[contains(@data-id,\"[NAME].SaveAndClose\")]",

        //MultiSelect
        "MultiSelect_DivContainer": ".//div[contains(@data-id,\"[NAME]-FieldSectionItemContainer\")]",
        "MultiSelect_InputSearch": ".//div[contains(@data-id,\"[NAME].fieldControl-LookupResultsDropdown_[NAME]_InputSearch\")]",
        "MultiSelect_SelectedRecord": ".//ul[contains(@data-id,\"[NAME].fieldControl-LookupResultsDropdown_[NAME]_SelectedRecordList\")]//li",
        "MultiSelect_SelectedRecord_Button": ".//ul[contains(@data-id,\"[NAME].fieldControl-LookupResultsDropdown_[NAME]\") and contains(@data-id, 'SelectedRecordList')]//li",
        "MultiSelect_SelectedRecord_Label": ".//ul[contains(@data-id,\"[NAME].fieldControl-LookupResultsDropdown_[NAME]_SelectedRecordList\")]/descendant::label",
        "MultiSelect_Flyout": "//div[contains(@id,\"[NAME].fieldControl|__flyoutRootNode_SimpleLookupControlFlyout\")]//ul",
        "MultiSelect_FlyoutList": "//div[contains(@id,\"[NAME].fieldControl|__flyoutRootNode_SimpleLookupControlFlyout\")]//li[descendant::label[contains(text(), \"{0}\")]]",
        "MultiSelect_ExpandCollapseButton": ".//button[contains(@data-id,\"[NAME].fieldControl-LookupResultsDropdown_[NAME]_expandCollapse\")]/descendant::label[not(text()=\"+0\")]",

        //Dashboard
        "Dashboard_Selector": "//span[contains(@id, 'Dashboard_Selector')]",
        "Dashboard_Item": "//li[contains(@title, '[NAME]')]",
        "Dashboard_Item_UCI": "//li[contains(@data-text, '[NAME]')]",

        //Business Process Flow
        "BPF_NextStage_UCI": "//li[contains(@id,'processHeaderStage')]",
        "BPF_Flyout_UCI": "//div[contains(@id,'businessProcessFlowFlyoutHeaderContainer')]",
        "BPF_NextStageButton_UCI": "//button[contains(@data-id,'nextButtonContainer')]",
        "BPF_SetActiveButton": "//button[contains(@data-id,'setActiveButton')]",
        "BPF_FieldName_UCI": "//input[contains(@id,'[NAME]')]",
        "BPF_FieldSectionItemContainer": ".//div[contains(@id, \'header_process_[NAME]-FieldSectionItemContainer\')]",
        "BPF_FormContext": "//div[contains(@id, \'ProcessStageControl-processHeaderStageFlyoutInnerContainer\')]",
        "BPF_TextFieldContainer": ".//div[contains(@data-lp-id, \'header_process_[NAME]\')]",
        "BPF_TextFieldLabel": "//label[contains(@id, \'header_process_[NAME]-field-label\')]",
        "BPF_BooleanFieldContainer": ".//input[contains(@data-id, \'header_process_[NAME].fieldControl-checkbox-toggle\')]",
        "BPF_DateTimeFieldContainer": ".//input[contains(@data-id, \'[NAME].fieldControl-date-time-input\')]",
        "BPF_FieldControlDateTimeInputUCI": ".//input[contains(@data-id,'[FIELD].fieldControl-date-time-input')]",
        "BPF_PinStageButton": "//button[contains(@id,'stageDockModeButton')]",
        "BPF_CloseStageButton": "//button[contains(@id,'stageContentClose')]",

        //Related Grid
        "Related_CommandBarButton": ".//li[contains(@aria-label, '[NAME]') and contains(@id,'SubGrid')]//button",
        "Related_CommandBarOverflowContainer": "//div[contains(@data-id, 'flyoutRootNode')]",
        "Related_CommandBarOverflowButton": ".//button[contains(@data-id, 'OverflowButton') and contains(@data-lp-id, 'SubGridAssociated')]",
        "Related_CommandBarSubButton": ".//button[contains(., '[NAME]')]",
        "Related_CommandBarButtonList": "//ul[contains(@data-lp-id, 'commandbar-SubGridAssociated')]",

        //Field
        "Field_ReadOnly": ".//*[@aria-readonly]",
        "Field_Required": ".//*[@aria-required]",
        "Field_RequiredIcon": ".//div[contains(@data-id, 'required-icon') or contains(@id, 'required-icon')]",

        //Dialogs
        "AssignDialog_ToggleField": "//label[contains(@data-id,'rdoMe_id.fieldControl-checkbox-inner-first')]",
        "AssignDialog_UserTeamLookupResults": "//ul[contains(@data-id,'systemuserview_id.fieldControl-LookupResultsDropdown_systemuserview_id_tab')]",
        "AssignDialog_OKButton": "//button[contains(@data-id, 'ok_id')]",
        "CloseOpportunityDialog_OKButton": "//button[contains(@data-id, 'ok_id')]",
        "CloseOpportunityDialog_CancelButton": "//button[contains(@data-id, 'cancel_id')]",
        "CloseActivityDialog_CloseButton": ".//button[contains(@data-id, 'ok_id')]",
        "CloseActivityDialog_CancelButton": ".//button[contains(@data-id, 'cancel_id')]",
        "Dialog_DialogContext": "//div[contains(@id,'dialogView') and contains(@role, 'dialog')]",
        "Dialog_ActualRevenue": "//input[contains(@data-id,'actualrevenue_id')]",
        "Dialog_CloseDate": "//input[contains(@data-id,'closedate_id')]",
        "Dialog_DescriptionId": "//input[contains(@data-id,'description_id')]",
        "Dialog_ConfirmButton": "//*[@id=\"confirmButton\"]",
        "Dialog_CancelButton": "//*[@id=\"cancelButton\"]",
        "DuplicateDetectionDialog_IgnoreAndSaveButton": "//button[contains(@data-id, 'ignore_save')]",
        "DuplicateDetectionDialog_CancelButton": "//button[contains(@data-id, 'close_dialog')]",
        "Dialog_SetStateDialog": "//div[@data-id=\"SetStateDialog\"]",
        "Dialog_SetStateActionButton": ".//button[@data-id=\"ok_id\"]",
        "Dialog_SetStateCancelButton": ".//button[@data-id=\"cancel_id\"]",
        "Dialog_PublishConfirmButton": "//*[@data-id=\"ok_id\"]",
        "Dialog_PublishCancelButton": "//*[@data-id=\"cancel_id\"]",
        "Dialog_SwitchProcessContainer": "//div[contains(@id,'switchProcess_id-FieldSectionItemContainer')]",
        "Entity_ActiveProcessGridControlContainer": "//div[contains(@data-lp-id,'activeProcessGridControlContainer')]",
        "Entity_SwitchProcessDialogOK": "//button[contains(@data-id,'ok_id')]",
        "SwitchProcess_Container": "//section[contains(@id, 'popupContainer')]",

        //QuickCreate
        "QuickCreate_FormContext": "//section[contains(@data-id,'quickCreateRoot')]",
        "QuickCreate_SaveButton": "//button[contains(@id,'quickCreateSaveBtn')]",
        "QuickCreate_SaveAndCloseButton": "//button[contains(@id,'quickCreateSaveAndCloseBtn')]",
        "QuickCreate_CancelButton": "//button[contains(@id,'quickCreateCancelBtn')]",

        //Lookup
        "Lookup_RelatedEntityLabel": "//li[contains(@title,'[NAME]') and contains(@data-id,'LookupResultsDropdown')]",
        "Lookup_ChangeViewButton": "//button[contains(@data-id,'changeViewBtn')]",
        "Lookup_ViewRows": "//li[contains(@data-id,'viewLineContainer')]",
        "Lookup_ResultRows": "//li[contains(@data-id,'LookupResultsDropdown') and contains(@data-id,'resultsContainer')]",
        "Lookup_NewButton": "//button[contains(@data-id,'addNewBtnContainer') and contains(@data-id,'LookupResultsDropdown')]",
        "Lookup_RecordList": ".//div[contains(@id,'RecordList') and contains(@role,'presentation')]",

        //Performance Width
        "Performance_Widget": "//div[@data-id='performance-widget']/div",
        "Performance_WidgetPage": "//div[@data-id='performance-widget']//span[contains(text(), '[NAME]')]"
    }
};

export enum LoginResult {
    Success,
    Failure,
    Redirect
}